apiVersion: v1
entries:
  bows-simpleApp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-07-31T15:57:03.899497+09:00"
    description: A Helm chart for Kubernetes
    digest: ab057dceacabb192eac16f9a60cedd83e6eab830ce0d45f465602e1b9cdf1e38
    name: bows-simpleApp
    type: application
    urls:
    - bows-simpleApp-0.1.0.tgz
    version: 0.1.0
generated: "2024-07-31T15:57:03.898864+09:00"
