apiVersion: v1
entries:
  bows-simpleApp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-07-31T16:29:30.316057+09:00"
    description: A Helm chart for Kubernetes
    digest: 9b27fa5848f24a654aa134f44ac5c81974c7be0f7c939a13f4fb4068a7fea23a
    name: bows-simpleApp
    type: application
    urls:
    - bows-simpleApp-0.1.0.tgz
    version: 0.1.0
generated: "2024-07-31T16:29:30.315076+09:00"
