apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: backend-deployment-{{ .Values.projectId }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      projectName: {{ .Values.projectName | lower }}
      projectId: {{ .Values.projectId | quote }}
      tier: backend
  template:
    metadata:
      labels:
        projectName: {{ .Values.projectName | lower }}
        projectId: {{ .Values.projectId | quote }}
        tier: backend
    spec:
      containers:
        - name: backend-server-{{ .Values.projectId }}
          image: {{ .Values.app.backend.image.name }}:{{ .Values.app.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.app.backend.port }}
          env:
            - name: MYSQL_HOST
              value: "db-service-{{ .Values.projectId }}"
            - name: MYSQL_DATABASE
              value: {{ .Values.app.db.env.MYSQL_DATABASE | quote }}
            - name: MYSQL_USER
              value: {{ .Values.app.db.env.MYSQL_USER | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.app.db.env.MYSQL_PASSWORD | quote }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: backend-service-{{ .Values.projectId }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend

spec:
  selector:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend
  ports:
    - protocol: {{ .Values.app.backend.protocol }}
      port: {{ .Values.app.backend.port }}
      targetPort: {{ .Values.app.backend.port }}