apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.projectId | quote }}-backend-deployment
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      projectName: {{ .Values.projectName | lower }}
      projectId: {{ .Values.projectId | quote }}
      tier: backend
  template:
    metadata:
      labels:
        projectName: {{ .Values.projectName | lower }}
        projectId: {{ .Values.projectId | quote }}
        tier: backend
    spec:
      containers:
        - name: {{ .Values.projectId | quote }}-backend-server
          image: {{ .Values.app.backend.image.name }}:{{ .Values.app.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.app.backend.port }}
          env:
            - name: MYSQL_HOST
              value: {{ printf "%s-db-service" (.Values.projectName | lower) | quote }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.projectId | quote }}-backend-service
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend

spec:
  selector:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: backend
  ports:
    - protocol: {{ .Values.app.backend.protocol }}
      port: {{ .Values.app.backend.port }}
      targetPort: {{ .Values.app.backend.port }}