apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectId | quote }}-db
  namespace: {{ .Values.namespace }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      projectName: {{ .Values.projectName | lower }}
      projectId: {{ .Values.projectId | quote }}
      tier: db
  template:
    metadata:
      labels:
        projectName: {{ .Values.projectName | lower }}
        projectId: {{ .Values.projectId | quote }}
        tier: db
    spec:
      containers:
        - name: {{ .Values.projectId | quote }}-db
          image: {{ .Values.app.db.image.name }}:{{ .Values.app.db.image.tag }}
          ports:
            - containerPort: {{ .Values.app.db.port }}
          env:
          {{- range $name, $value := .Values.app.db.env }}
            - name: {{ $name }}
              value: {{ $value }}
          {{- end }}
          volumeMounts:
            - name:  {{ .Values.projectId | quote }}-storage
              mountPath: /var/lib/{{ .Values.projectId | quote }}/storage
      volumes:
        - name: {{ .Values.projectId | quote }}-storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.projectId | quote }}-db-service
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: db
spec:
  selector:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: db
  ports:
    - protocol: {{ .Values.app.db.protocol }}
      port: {{ .Values.app.db.port }}
      targetPort: {{ .Values.app.db.port }}