apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectId }}-frontend-ingress
  namespace: {{ .Values.namespace }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }}
      kind: Rule
      services:
        - name: {{ .Values.projectId }}-frontend-service
          port: {{ .Values.app.frontend.port }}

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectId }}-backend-ingress
  namespace: {{ .Values.namespace }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }} && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ .Values.projectId }}-backend-service
          port: {{ .Values.app.backend.port }}