apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-{{ .Values.projectId }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: certificate-{{ .Values.projectId }}
  issuerRef:
    name: letsencrypt-bows
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.domain }}

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-{{ .Values.projectId }}
  namespace: {{ .Values.namespace }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }}
      kind: Rule
      services:
        - name: frontend-service-{{ .Values.projectId }}
          port: {{ .Values.app.frontend.port }}
  tls:
    secretName: certificate-{{ .Values.projectId }}

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingress-{{ .Values.projectId }}
  namespace: {{ .Values.namespace }}
  labels:
    projectName: {{ .Values.projectName | lower }}
    projectId: {{ .Values.projectId | quote }}
    tier: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }} && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: backend-service-{{ .Values.projectId }}
          port: {{ .Values.app.backend.port }}
  tls:
    secretName: certificate-{{ .Values.projectId }}